Update interviewer.jsp
In Line 31 the noConflict for jquery was added, to get rid of the errormessage in prototype:
prototype.js:6598 Uncaught TypeError: element.dispatchEvent is not a function